functionality:
  name: "fastqc"
  namespace: "qc"
  version: "0.11.0"
  arguments:
  - type: "string"
    name: "--mode"
    alternatives:
    - "-m"
    description: "The mode in which the component works. Can be either files or dir."
    info: null
    default:
    - "files"
    required: false
    choices:
    - "files"
    - "dir"
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Directory containing input fastq files."
    info: null
    example:
    - "fastq_dir"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    description: "Output directory to write reports to."
    info: null
    example:
    - "qc"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--threads"
    alternatives:
    - "-t"
    description: "Specifies the number of files which can be processed simultaneously.\
      \ Each thread will be allocated 250MB of\nmemory.\n"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "Fastqc component, please see https://www.bioinformatics.babraham.ac.uk/projects/fastqc/.\
    \ This component can take one or more files (by means of shell globbing) or a\
    \ complete directory.\n"
  test_resources:
  - type: "bash_script"
    path: "test.sh"
    is_executable: true
  - type: "file"
    path: "resources_test/cellranger_tiny_fastq/cellranger_tiny_fastq"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ubuntu:22.04"
  target_organization: "openpipelines-bio/openpipeline"
  target_registry: "viash-hub.com:5050"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://viash-hub.com/openpipelines-bio/openpipeline"
  setup:
  - type: "apt"
    packages:
    - "fastqc"
    interactive: false
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "lowcpu"
    - "midmem"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/qc/fastqc/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/openpipeline/openpipeline/target/nextflow/qc/fastqc"
  executable: "/home/runner/work/openpipeline/openpipeline/target/nextflow/qc/fastqc/fastqc"
  viash_version: "0.7.5"
  git_commit: "125f0afa4ac570f5c381f84dd0bef0ad16c9865b"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
