functionality:
  name: "parallel_qc"
  namespace: "workflows"
  version: "dev"
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "fastq files"
    info: null
    example:
    - "file1.tar.gz;file2.tar.gz"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ";"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    description: "Output directory to write reports to."
    info: null
    example:
    - "qc"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
    entrypoint: "run_wf"
  description: "A workflow for running fastqc (in parallel) using a\ncomponents from\
    \ OpenPipelines and aggregating those\nin one report using multiqc.\n"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  dependencies:
  - name: "qc/fastqc"
    repository:
      type: "vsh"
      name: ""
      repo: "openpipelines-bio/openpipeline"
      tag: "0.11.0"
      localPath: "/tmp/viash_hub_repo18387161669101694408"
    foundConfigPath: "/tmp/viash_hub_repo18387161669101694408/target/nextflow/qc/fastqc/.config.vsh.yaml"
    configInfo:
      functionalityName: "fastqc"
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.7.5"
      config: "/home/runner/work/openpipeline/openpipeline/src/qc/fastqc/config.vsh.yaml"
      functionalityNamespace: "qc"
      output: "/home/runner/work/openpipeline/openpipeline/target/nextflow/qc/fastqc"
      platform: "nextflow"
      git_commit: "125f0afa4ac570f5c381f84dd0bef0ad16c9865b"
      executable: "/home/runner/work/openpipeline/openpipeline/target/nextflow/qc/fastqc/fastqc"
    writtenPath: "/Users/toni/code/projects/viash-hub/demo/target/dependencies/vsh/openpipelines-bio/openpipeline/0.11.0/../../../../tmp/viash_hub_repo18387161669101694408/target/nextflow/qc/fastqc"
  - name: "qc/multiqc"
    repository:
      type: "vsh"
      name: ""
      repo: "openpipelines-bio/openpipeline"
      tag: "0.11.0"
      localPath: "/tmp/viash_hub_repo7720689368068600917"
    foundConfigPath: "/tmp/viash_hub_repo7720689368068600917/target/nextflow/qc/multiqc/.config.vsh.yaml"
    configInfo:
      functionalityName: "multiqc"
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.7.5"
      config: "/home/runner/work/openpipeline/openpipeline/src/qc/multiqc/config.vsh.yaml"
      functionalityNamespace: "qc"
      output: "/home/runner/work/openpipeline/openpipeline/target/nextflow/qc/multiqc"
      platform: "nextflow"
      git_commit: "125f0afa4ac570f5c381f84dd0bef0ad16c9865b"
      executable: "/home/runner/work/openpipeline/openpipeline/target/nextflow/qc/multiqc/multiqc"
    writtenPath: "/Users/toni/code/projects/viash-hub/demo/target/dependencies/vsh/openpipelines-bio/openpipeline/0.11.0/../../../../tmp/viash_hub_repo7720689368068600917/target/nextflow/qc/multiqc"
  - name: "split/expand"
    repository:
      type: "vsh"
      name: ""
      repo: "data-intuitive/vsh_utils"
      tag: "main"
      localPath: "/tmp/viash_hub_repo11385814683362704779"
    foundConfigPath: "/tmp/viash_hub_repo11385814683362704779/target/nextflow/split/expand/.config.vsh.yaml"
    configInfo:
      functionalityName: "expand"
      git_remote: "git@viash-hub.com:data-intuitive/vsh_utils.git"
      viash_version: "0.8.0"
      config: "/Users/toni/code/projects/viash-hub/vsh_utils/src/split/expand/config.vsh.yaml"
      functionalityNamespace: "split"
      output: "/Users/toni/code/projects/viash-hub/vsh_utils/target/nextflow/split/expand"
      platform: "nextflow"
      git_commit: "f3f9b7865c72ac17c5607f1adf73caed07819521"
      executable: "/Users/toni/code/projects/viash-hub/vsh_utils/target/nextflow/split/expand/main.nf"
    writtenPath: "/Users/toni/code/projects/viash-hub/demo/target/dependencies/vsh/data-intuitive/vsh_utils/main/../../../../tmp/viash_hub_repo11385814683362704779/target/nextflow/split/expand"
  - name: "join/vsh_toList"
    repository:
      type: "vsh"
      name: ""
      repo: "data-intuitive/vsh_utils"
      tag: "main"
      localPath: "/tmp/viash_hub_repo15029941886826839711"
    foundConfigPath: "/tmp/viash_hub_repo15029941886826839711/target/nextflow/join/vsh_toList/.config.vsh.yaml"
    configInfo:
      functionalityName: "vsh_toList"
      git_remote: "git@viash-hub.com:data-intuitive/vsh_utils.git"
      viash_version: "0.8.0"
      config: "/Users/toni/code/projects/viash-hub/vsh_utils/src/join/vsh_toList/config.vsh.yaml"
      functionalityNamespace: "join"
      output: "/Users/toni/code/projects/viash-hub/vsh_utils/target/nextflow/join/vsh_toList"
      platform: "nextflow"
      git_commit: "f3f9b7865c72ac17c5607f1adf73caed07819521"
      executable: "/Users/toni/code/projects/viash-hub/vsh_utils/target/nextflow/join/vsh_toList/main.nf"
    writtenPath: "/Users/toni/code/projects/viash-hub/demo/target/dependencies/vsh/data-intuitive/vsh_utils/main/../../../../tmp/viash_hub_repo15029941886826839711/target/nextflow/join/vsh_toList"
  - name: "join/assemble"
    repository:
      type: "vsh"
      name: ""
      repo: "data-intuitive/vsh_utils"
      tag: "main"
      localPath: "/tmp/viash_hub_repo10815051608847371098"
    foundConfigPath: "/tmp/viash_hub_repo10815051608847371098/target/nextflow/join/assemble/.config.vsh.yaml"
    configInfo:
      functionalityName: "assemble"
      git_remote: "git@viash-hub.com:data-intuitive/vsh_utils.git"
      viash_version: "0.8.0"
      config: "/Users/toni/code/projects/viash-hub/vsh_utils/src/join/assemble/config.vsh.yaml"
      functionalityNamespace: "join"
      output: "/Users/toni/code/projects/viash-hub/vsh_utils/target/nextflow/join/assemble"
      platform: "nextflow"
      git_commit: "f3f9b7865c72ac17c5607f1adf73caed07819521"
      executable: "/Users/toni/code/projects/viash-hub/vsh_utils/target/nextflow/join/assemble/assemble"
    writtenPath: "/Users/toni/code/projects/viash-hub/demo/target/dependencies/vsh/data-intuitive/vsh_utils/main/../../../../tmp/viash_hub_repo10815051608847371098/target/nextflow/join/assemble"
  repositories:
  - type: "vsh"
    name: "openpipeline"
    repo: "openpipelines-bio/openpipeline"
    tag: "0.11.0"
    localPath: ""
  - type: "vsh"
    name: "vsh_utils"
    repo: "data-intuitive/vsh_utils"
    tag: "main"
    localPath: ""
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
info:
  config: "/Users/toni/code/projects/viash-hub/demo/src/workflows/parallel_qc/config.vsh.yaml"
  platform: "nextflow"
  output: "/Users/toni/code/projects/viash-hub/demo/target/nextflow/workflows/parallel_qc"
  executable: "/Users/toni/code/projects/viash-hub/demo/target/nextflow/workflows/parallel_qc/main.nf"
  viash_version: "0.8.2"
  git_commit: "1f19979d1018041ef750baac035d8dbf538ffefd"
  git_remote: "https://github.com/viash-io/viash_hub_demo.git"
