functionality:
  name: transpose
  namespace: utils
  description: |
      Expand the input wildcard, i.e. convert the input channel with one event
        `[ _, [ input: <list_of_files> ] ]`
      into a channel with seperate events of the format:
        `[ <filename>, [ input: <file> ] ]`
      This involves some Nextflow and Groovy magic.

  arguments:
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      required: true
      multiple: true
      multiple_sep: ";"
      description: Input files with ';' as delimiter
      example: file1;file2;... 
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      direction: output
      required: true
      description: output files, one per Channel event
      example: file1

  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf

platforms:
  - type: nextflow
