functionality:
  name: "transpose"
  namespace: "utils"
  version: "dev"
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Input files with ';' as delimiter"
    info: null
    example:
    - "file1;file2;..."
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ";"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    description: "output files, one per Channel event"
    info: null
    example:
    - "file1"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
    entrypoint: "run_wf"
  description: "Expand the input wildcard, i.e. convert the input channel with one\
    \ event\n  `[ _, [ input: <list_of_files> ] ]`\ninto a channel with seperate events\
    \ of the format:\n  `[ <filename>, [ input: <file> ] ]`\nThis involves some Nextflow\
    \ and Groovy magic.\n"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
info:
  config: "/Users/toni/code/projects/viash-hub/demo/src/utils/transpose/config.vsh.yaml"
  platform: "nextflow"
  output: "/Users/toni/code/projects/viash-hub/demo/target/nextflow/utils/transpose"
  executable: "/Users/toni/code/projects/viash-hub/demo/target/nextflow/utils/transpose/main.nf"
  viash_version: "0.8.0"
  git_commit: "1f9cf7387c98fbbb91a217fffa5cc9ca523b6a8e"
  git_remote: "https://github.com/viash-io/viash_hub_demo.git"
