functionality:
  name: parallel_qc
  namespace: workflows
  description: |
    A workflow for running fastqc (in parallel) using a
    components from OpenPipelines and aggregating those
    in one report using multiqc.

  arguments:
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      required: true
      multiple: true
      multiple_sep: ";"
      description: fastq files
      example: file1.tar.gz;file2.tar.gz 
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      direction: output
      required: true
      description: Output directory to write reports to.
      example: qc/

  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf

  dependencies: 
    - name: qc/fastqc
      repository: openpipeline
    - name: qc/multiqc
      repository: openpipeline
    - name: split/expand
      repository: vsh_utils
    - name: join/vsh_toList
      repository: vsh_utils
    - name: join/assemble
      repository: vsh_utils

  repositories:
    - name: openpipeline
      type: vsh
      repo: openpipelines-bio/openpipeline
      tag: 0.11.0
    - name: vsh_utils
      type: vsh
      repo: data-intuitive/vsh_utils
      tag: v0.1.0
    # - name: local
    #   type: local

platforms:
  - type: nextflow
